# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Lindsey's Blog
email: matthew.r.lindsey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
       This is Matt Lindsey blog associated with www.matthewrlindsey.org.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: matthewrlindsey
github_username:  mattlindsey
exclude:
  - site

# Build settings
markdown: kramdown
